gtaxl: libshim_camera: Revert "Convert Android.mk to Android.bp"
This reverts commit 7ec86b274c78b255cd18bde94ef56a1867f5a4ea.

The conversion to Android.bp causes this error with the build system
when trying to build for certain other devices, in this case, gta4xlwifi:

[100% 1013/1013] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
error: device/samsung/gtaxl-common/shims/libshim_camera/Android.bp:16:1: module "libexynoscamera_shim" variant "android_vendor.32_arm_armv8-a_cortex-a53_shared": non-VNDK module should not link to "libgui" which has `private: true`
18:05:24 soong bootstrap failed with: exit status 1

No idea for a more proper fix (if there's any), so just revert it.

Change-Id: I93426d2f64811483600134591e37e319b290d4fe